development:
  adapter: sqlite3
  database: db/dev.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

cucumber:
  adapter: sqlite3
  database: db/test.sqlite3

culerity:
  adapter: sqlite3
  database: db/test.sqlite3
